import one from "../public/1.png";
import two from "../public/2.png";
import three from "../public/3.png";
import four from "../public/4.png";
import five from "../public/5.png";
import six from "../public/6.png";

export const flowers_category = [
    {name: "Магнолії", image: one, new: false, popular: true},
    {name: "Ялина - Picea", image: two, new: true, popular: true},
    {name: "Ялиці - Abies", image: three, new: true, popular: true},
    {name: "Листяні кущі", image: four, new: false, popular: false},
    {name: "Японські клени", image: five, new: false, popular: false},
    {name: "Штамбові авойні рослини", image: six, new: false, popular: true}]
export const flowers = [
    {name: "Квітка Амаріліс", category: "Магнолії", image: one, new: false, price: 4532120},
    {name: "Квітка Бегонія", category: "Ялина - Picea", image: two, new: false, price: 280},
    {name: "Квітка Калла", category: "Ялиці - Abies", image: three, new: true, price: 320},
    {name: "Квітка Гербера", category: "Листяні кущі", image: four, new: false, price: 180},
    {name: "Квітка Даля", category: "Японські клени", image: five, new: true, price: 360},
    {name: "Квітка Ехінацея", category: "Штамбові авойні рослини", image: six, new: false, price: 210},
    {name: "Квітка Флокс", category: "Магнолії", image: one, new: true, price: 300},
    {name: "Квітка Жоржина", category: "Ялина - Picea", image: two, new: false, price: 340},
    {name: "Квітка Ірис", category: "Ялиці - Abies", image: three, new: false, price: 260},
    {name: "Квітка Лілія", category: "Листяні кущі", image: four, new: true, price: 380},
    {name: "Квітка Маргаритка", category: "Японські клени", image: five, new: false, price: 200},
    {name: "Квітка Нарцис", category: "Штамбові авойні рослини", image: six, new: true, price: 290},
    {name: "Квітка Орхідея", category: "Магнолії", image: one, new: false, price: 420},
    {name: "Квітка Півонія", category: "Ялина - Picea", image: two, new: true, price: 330},
    {name: "Квітка Рожева троянда", category: "Ялиці - Abies", image: three, new: false, price: 370},
    {name: "Квітка Соняшник", category: "Листяні кущі", image: four, new: true, price: 250},
    {name: "Квітка Тюльпан", category: "Японські клени", image: five, new: false, price: 310},
      {name: "Квітка Гербера", category: "Листяні кущі", image: four, new: false, price: 180},
    {name: "Квітка Даля", category: "Японські клени", image: five, new: true, price: 360},
    {name: "Квітка Ехінацея", category: "Штамбові авойні рослини", image: six, new: false, price: 210},
    {name: "Квітка Флокс", category: "Магнолії", image: one, new: true, price: 300},
    {name: "Квітка Жоржина", category: "Ялина - Picea", image: two, new: false, price: 340},
    {name: "Квітка Ірис", category: "Ялиці - Abies", image: three, new: false, price: 260},
    {name: "Квітка Лілія", category: "Листяні кущі", image: four, new: true, price: 380},
    {name: "Квітка Маргаритка", category: "Японські клени", image: five, new: false, price: 200},
    {name: "Квітка Нарцис", category: "Штамбові авойні рослини", image: six, new: true, price: 290},
    {name: "Квітка Орхідея", category: "Магнолії", image: one, new: false, price: 420},
    {name: "Квітка Півонія", category: "Ялина - Picea", image: two, new: true, price: 330},
    {name: "Квітка Рожева троянда", category: "Ялиці - Abies", image: three, new: false, price: 370},
    {name: "Квітка Соняшник", category: "Листяні кущі", image: four, new: true, price: 250},
    {name: "Квітка Тюльпан", category: "Японські клени", image: five, new: false, price: 310},
      {name: "Квітка Гербера", category: "Листяні кущі", image: four, new: false, price: 180},
    {name: "Квітка Даля", category: "Японські клени", image: five, new: true, price: 360},
    {name: "Квітка Ехінацея", category: "Штамбові авойні рослини", image: six, new: false, price: 210},
    {name: "Квітка Флокс", category: "Магнолії", image: one, new: true, price: 300},
    {name: "Квітка Жоржина", category: "Ялина - Picea", image: two, new: false, price: 340},
    {name: "Квітка Ірис", category: "Ялиці - Abies", image: three, new: false, price: 260},
    {name: "Квітка Лілія", category: "Листяні кущі", image: four, new: true, price: 380},
    {name: "Квітка Маргаритка", category: "Японські клени", image: five, new: false, price: 200},
    {name: "Квітка Нарцис", category: "Штамбові авойні рослини", image: six, new: true, price: 290},
    {name: "Квітка Орхідея", category: "Магнолії", image: one, new: false, price: 420},
    {name: "Квітка Півонія", category: "Ялина - Picea", image: two, new: true, price: 330},
    {name: "Квітка Рожева троянда", category: "Ялиці - Abies", image: three, new: false, price: 370},
    {name: "Квітка Соняшник", category: "Листяні кущі", image: four, new: true, price: 250},
    {name: "Квітка Тюльпан", category: "Японські клени", image: five, new: false, price: 310},
      {name: "Квітка Гербера", category: "Листяні кущі", image: four, new: false, price: 180},
    {name: "Квітка Даля", category: "Японські клени", image: five, new: true, price: 360},
    {name: "Квітка Ехінацея", category: "Штамбові авойні рослини", image: six, new: false, price: 210},
    {name: "Квітка Флокс", category: "Магнолії", image: one, new: true, price: 300},
    {name: "Квітка Жоржина", category: "Ялина - Picea", image: two, new: false, price: 340},
    {name: "Квітка Ірис", category: "Ялиці - Abies", image: three, new: false, price: 260},
    {name: "Квітка Лілія", category: "Листяні кущі", image: four, new: true, price: 380},
    {name: "Квітка Маргаритка", category: "Японські клени", image: five, new: false, price: 200},
    {name: "Квітка Нарцис", category: "Штамбові авойні рослини", image: six, new: true, price: 290},
    {name: "Квітка Орхідея", category: "Магнолії", image: one, new: false, price: 420},
    {name: "Квітка Півонія", category: "Ялина - Picea", image: two, new: true, price: 330},
    {name: "Квітка Рожева троянда", category: "Ялиці - Abies", image: three, new: false, price: 370},
    {name: "Квітка Соняшник", category: "Листяні кущі", image: four, new: true, price: 250},
    {name: "Квітка Тюльпан", category: "Японські клени", image: five, new: false, price: 310},
    {name: "Квітка Удод", category: "Штамбові авойні рослини", image: six, new: false, price: 230}
];
